from . import (
    mail_channel,
    res_config_settings,
    res_partner,
    sendpulse_connect,
    sendpulse_facebook_page,
    sendpulse_faq_entry,
    sendpulse_identify_wizard,
    sendpulse_message,
    sendpulse_oauth,
    sendpulse_privacy_consent_log,
    sendpulse_public_template,
    sendpulse_rodo,
    sendpulse_telegram_notify,
)
